apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp4dev
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
        - pathType: Prefix
          path: /mail
          backend:
            service:
              name: smtp4dev
              port:
                number: 80
---
# https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: nginx-ingress-controller
spec:
  listener:
    name: smtp-tcp # name of global config listener
    protocol: TCP
  upstreams:
    - name: smtp4dev # name of service
      service: smtp4dev
      port: 25
  action:
    pass: smtp4dev
